travis:
  secure:
    BINSTAR_TOKEN: hEckR2C2CzZffRBqyqDIOyLVwMdcw3OzgRhALEPYq+zazBb5sgEGS6gF/e4EEEd1jhcnN+g1CwZuRLyIUMAXnJ9g7zcIin+kjFTE2dCODPdSJt3GE3I/swa42sKFqbudGxlGjshk/uDYGAeT/tMFZxVhm0DbQkQHX7fiZUUf6w/jxYLrnv/6JTV7VhMnHr5MVjrr1ypqT8IfEttjEif1HEA5/4s9z++TLUqi0rpdgofOdIp3b3OkvY5cSDh0nfyg/u0PH8+DISP9RIYtgaU70ZbuuZiBkqtd1oX3SWSPRPFdktAyzq9oxDHHgt3gpWnvXbD0QzKnWCBc2Xwazpn9AOAe6MHxiCgkd/Ac/rfntvsqphfhHVAkxd2A5O86FGvGjWuZM7dOQ6gPNjF1ea3HrZeF7ROuzvAcmU5orqu7V9/LkZI5vZhaIXvVDJ6+SWhb9HbcI3mP4UM9wYLcYDb+lnDl7A3sK01nqOO2rjKPNcyF+AP65p44vNyoe0xM997+noc9aeTXpdQCi2wJc3TZXhYNzcyrrcl/6rZSkHB/NnF2benYlmYpau3gOW1RtzBZ31Yz9Jfs5mOaSY0fqe/9n/4MlQlIp0YaHBZWw9RH/poB5IZtAErbjiHLMylwSxb2VpZzqNfpRHw1W+q8dbdO3DAQ6ZxXk8nqQ2cTPpmEPXw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
